FROM mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye

RUN apt-get update && apt-get install gnupg2 -y

RUN git config --global --add safe.directory /workspaces/frontend

ENTRYPOINT sleep infinity 